services:
  web:
    build: './app'
    command: sh -c "python main.py"
    ports:
      - '5000:5000'
    volumes:
      - ./app:/app
    restart: on-failure
  db:
    image: mysql:8.0
    ports:
      - "3305:3306"
    restart: always
    environment:
      MYSQL_DATABASE: rudy_db
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local